// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e174c9286f577d89 "Innermost AI (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
} from "./chunks/chunk-WCMW3GCM.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:call-or-text
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/VbXXdpBGGoGG4JLpEYUT/c0mmhkFw3pME3KmRhCBR/tXKcvVMmL.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/yeuhO00zzf0BPXItmwK9/2SgUPdVEHq8z5YF3d9rb/LuUHh3uUf.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = [
	"CRbP10Ds7",
	"GWxnkbO6z",
	"onIQ6cqVJ",
	"b268i2dTX",
	"yLsgqhpiR",
	"HHXGrB9Qq",
	"oZDuSScXV",
	"RlMihXU8D",
];
var serializationHash = "framer-0COZ1";
var variantClassNames = {
	b268i2dTX: "framer-v-1232g0g",
	CRbP10Ds7: "framer-v-1cv53sz",
	GWxnkbO6z: "framer-v-1bpg8e1",
	HHXGrB9Qq: "framer-v-2lwrq0",
	onIQ6cqVJ: "framer-v-wuo9a7",
	oZDuSScXV: "framer-v-pse23o",
	RlMihXU8D: "framer-v-1cvzj6e",
	yLsgqhpiR: "framer-v-h404o6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 10,
	y: 0,
};
var transition2 = {
	delay: 0.1,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 10,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition3 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 350,
	type: "spring",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 60,
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 100,
};
var transition4 = {
	damping: 50,
	delay: 0.4,
	mass: 1,
	stiffness: 350,
	type: "spring",
};
var animation5 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 100,
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var animation6 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 100,
};
var transition5 = {
	damping: 50,
	delay: 0.6,
	mass: 1,
	stiffness: 350,
	type: "spring",
};
var animation7 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 100,
};
var animation8 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var animation9 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 30,
};
var animation10 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 150,
	y: 0,
};
var animation11 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 150,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Male medium": "HHXGrB9Qq",
	"Male phone": "RlMihXU8D",
	"Male tablet": "oZDuSScXV",
	Desktop: "CRbP10Ds7",
	Male: "yLsgqhpiR",
	Medium: "GWxnkbO6z",
	Phone: "b268i2dTX",
	Tablet: "onIQ6cqVJ",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CRbP10Ds7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CRbP10Ds7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["yLsgqhpiR", "HHXGrB9Qq", "oZDuSScXV", "RlMihXU8D"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (
			["yLsgqhpiR", "HHXGrB9Qq", "oZDuSScXV", "RlMihXU8D"].includes(baseVariant)
		)
			return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1cv53sz",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"CRbP10Ds7"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgb(247, 245, 242)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-66f6c013-6cdf-4180-9fee-2a865eb558bd, rgb(247, 245, 242))",
							borderBottomLeftRadius: 48,
							borderBottomRightRadius: 48,
							borderTopLeftRadius: 48,
							borderTopRightRadius: 48,
							...style,
						}}
						{...addPropertyOverrides(
							{
								b268i2dTX: {
									"data-framer-name": "Phone",
								},
								GWxnkbO6z: {
									"data-framer-name": "Medium",
								},
								HHXGrB9Qq: {
									"data-framer-name": "Male medium",
								},
								onIQ6cqVJ: {
									"data-framer-name": "Tablet",
								},
								oZDuSScXV: {
									"data-framer-name": "Male tablet",
								},
								RlMihXU8D: {
									"data-framer-name": "Male phone",
								},
								yLsgqhpiR: {
									"data-framer-name": "Male",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-101n4e"}
							data-framer-name={"title+tagline+grid"}
							layoutDependency={layoutDependency}
							layoutId={"g18dY8DWD"}
						>
							<motion.div
								className={"framer-njv8nm"}
								data-framer-name={"Hook"}
								layoutDependency={layoutDependency}
								layoutId={"Z58bxGaC8"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-15yuobz"}
									data-framer-name={"Text anytime, day or night"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"CjJ967chg"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											HHXGrB9Qq: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1gk582c"}
															data-styles-preset={"y0TAMp3V0"}
															style={{
																"--framer-text-alignment": "left",
															}}
														>
															{"Talk to your guide anytime"}
														</motion.h3>
													</React.Fragment>
												),
											},
											oZDuSScXV: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1gk582c"}
															data-styles-preset={"y0TAMp3V0"}
															style={{
																"--framer-text-alignment": "left",
															}}
														>
															{"Talk to your guide anytime"}
														</motion.h3>
													</React.Fragment>
												),
											},
											RlMihXU8D: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1gk582c"}
															data-styles-preset={"y0TAMp3V0"}
															style={{
																"--framer-text-alignment": "left",
															}}
														>
															{"Talk to your guide anytime"}
														</motion.h3>
													</React.Fragment>
												),
											},
											yLsgqhpiR: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1gk582c"}
															data-styles-preset={"y0TAMp3V0"}
															style={{
																"--framer-text-alignment": "left",
															}}
														>
															{"Talk to your guide anytime"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-1gk582c"}
											data-styles-preset={"y0TAMp3V0"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Text anytime, "}
											<motion.br />
											{"day or night"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1racp9r"}
									data-framer-name={
										"A private, secure space to share what\u2019s on your mind and get hyper-personalized support when you need it, with someone who listens closely and responds with guidance."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"zuxZsYSSi"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											HHXGrB9Qq: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i5cls4"}
															data-styles-preset={"EPQDnqDHg"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Call when you want to process things in real time, share what\u2019s on your mind, or simply feel that extra bit of connection. Your guide is there to listen and walk through it with you, step by step."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											oZDuSScXV: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i5cls4"}
															data-styles-preset={"EPQDnqDHg"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Call when you want to process things in real time, share what\u2019s on your mind, or simply feel that extra bit of connection. Your guide is there to listen and walk through it with you, step by step."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											RlMihXU8D: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i5cls4"}
															data-styles-preset={"EPQDnqDHg"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Call when you want to process things in real time, share what\u2019s on your mind, or simply feel that extra bit of connection. Your guide is there to listen and walk through it with you, step by step."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											yLsgqhpiR: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i5cls4"}
															data-styles-preset={"EPQDnqDHg"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Call when you want to process things in real time, share what\u2019s on your mind, or simply feel that extra bit of connection. Your guide is there to listen and walk through it with you, step by step."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1i5cls4"}
											data-styles-preset={"EPQDnqDHg"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
											}}
										>
											{
												"A private, secure space to share what\u2019s on your mind and get hyper-personalized support when you need it, with someone who listens closely and responds with guidance."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-15jb400"}
							layoutDependency={layoutDependency}
							layoutId={"FUyO4BLme"}
						>
							<ImageWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 60 + 0,
									),
									pixelHeight: 3478,
									pixelWidth: 1680,
									positionX: "center",
									positionY: "center",
									sizes: "420px",
									src: "https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478",
									srcSet:
										"https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?scale-down-to=2048&width=1680&height=3478 989w,https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478 1680w",
								}}
								className={"framer-1w59wi7"}
								data-framer-name={"iphone"}
								layoutDependency={layoutDependency}
								layoutId={"JxdxKFTmO"}
								{...addPropertyOverrides(
									{
										b268i2dTX: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														60 +
														(((componentViewport?.height || 1056) -
															60 -
															887.8) /
															2 +
															240.8 +
															40) +
														0,
												),
												pixelHeight: 3478,
												pixelWidth: 1680,
												positionX: "center",
												positionY: "center",
												sizes: "310px",
												src: "https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478",
												srcSet:
													"https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?scale-down-to=2048&width=1680&height=3478 989w,https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478 1680w",
											},
										},
										HHXGrB9Qq: {
											__framer__animate: {
												transition: transition3,
											},
											__framer__enter: animation2,
											__framer__exit: animation3,
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 60 + 0,
												),
												pixelHeight: 3718,
												pixelWidth: 1920,
												sizes: "420px",
												src: "https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718",
												srcSet:
													"https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=1024&width=1920&height=3718 528w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=2048&width=1920&height=3718 1057w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718 1920w",
											},
										},
										onIQ6cqVJ: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														60 +
														(((componentViewport?.height || 892) - 60 - 858.8) /
															2 +
															240.8 +
															40) +
														0,
												),
												pixelHeight: 3478,
												pixelWidth: 1680,
												positionX: "center",
												positionY: "center",
												sizes: "420px",
												src: "https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478",
												srcSet:
													"https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?scale-down-to=2048&width=1680&height=3478 989w,https://framerusercontent.com/images/Ugxjcjed9cbIrkDlRayoNWpccPs.png?width=1680&height=3478 1680w",
											},
										},
										oZDuSScXV: {
											__framer__animate: {
												transition: transition3,
											},
											__framer__enter: animation2,
											__framer__exit: animation3,
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 60 + 308.8 + 0,
												),
												pixelHeight: 3718,
												pixelWidth: 1920,
												sizes: "420px",
												src: "https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718",
												srcSet:
													"https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=1024&width=1920&height=3718 528w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=2048&width=1920&height=3718 1057w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718 1920w",
											},
										},
										RlMihXU8D: {
											__framer__animate: {
												transition: transition3,
											},
											__framer__enter: animation2,
											__framer__exit: animation3,
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 60 + 280.8 + 0,
												),
												pixelHeight: 3718,
												pixelWidth: 1920,
												sizes: `calc(${componentViewport?.width || "100vw"} - 46px)`,
												src: "https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718",
												srcSet:
													"https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=1024&width=1920&height=3718 528w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=2048&width=1920&height=3718 1057w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718 1920w",
											},
										},
										yLsgqhpiR: {
											__framer__animate: {
												transition: transition3,
											},
											__framer__enter: animation2,
											__framer__exit: animation3,
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 60 + 0,
												),
												pixelHeight: 3718,
												pixelWidth: 1920,
												sizes: "420px",
												src: "https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718",
												srcSet:
													"https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=1024&width=1920&height=3718 528w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?scale-down-to=2048&width=1920&height=3718 1057w,https://framerusercontent.com/images/yfhtpWJE6Iq0zWZj6INOJE71dWU.png?width=1920&height=3718 1920w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition4,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation4}
								__framer__exit={animation5}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-10scqko"}
								data-border={true}
								data-framer-name={"Ai white"}
								layoutDependency={layoutDependency}
								layoutId={"BX2GA58jV"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(255, 255, 255, 0.7)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgba(255, 255, 255, 0.8)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									boxShadow: "0px 0px 13px 0px rgba(0, 0, 0, 0.07)",
								}}
								transformTemplate={transformTemplate1}
								variants={{
									RlMihXU8D: {
										borderBottomLeftRadius: 14,
										borderBottomRightRadius: 14,
										borderTopLeftRadius: 14,
										borderTopRightRadius: 14,
									},
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "stretch",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												60 +
												(((componentViewport?.height || 639) - 60) *
													0.9983 *
													0.4982698961937718 -
													92) +
												20,
										),
										pixelHeight: 160,
										pixelWidth: 160,
										positionX: "center",
										positionY: "center",
										src: "https://framerusercontent.com/images/cHEFJUA40cMy7DBl9qPfL7HDf9o.png?width=160&height=160",
									}}
									className={"framer-79gxlc"}
									data-framer-name={"Ellipse 52"}
									layoutDependency={layoutDependency}
									layoutId={"q10_olnCv"}
									style={{
										borderBottomLeftRadius: "100%",
										borderBottomRightRadius: "100%",
										borderTopLeftRadius: "100%",
										borderTopRightRadius: "100%",
									}}
									{...addPropertyOverrides(
										{
											b268i2dTX: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															(((componentViewport?.height || 1056) -
																60 -
																887.8) /
																2 +
																240.8 +
																40) +
															402 +
															20,
													),
													pixelHeight: 160,
													pixelWidth: 160,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/cHEFJUA40cMy7DBl9qPfL7HDf9o.png?width=160&height=160",
												},
											},
											HHXGrB9Qq: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															(((componentViewport?.height || 639) - 60) *
																0.9983 *
																0.46020761245674763 -
																92) +
															20,
													),
													pixelHeight: 121,
													pixelWidth: 121,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/mLGrHvf17TaprE2LO1GYqf0Vg.png?width=121&height=121",
												},
											},
											onIQ6cqVJ: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															(((componentViewport?.height || 892) -
																60 -
																858.8) /
																2 +
																240.8 +
																40) +
															208 +
															20,
													),
													pixelHeight: 160,
													pixelWidth: 160,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/cHEFJUA40cMy7DBl9qPfL7HDf9o.png?width=160&height=160",
												},
											},
											oZDuSScXV: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 60 + 308.8 + 174 + 20,
													),
													pixelHeight: 121,
													pixelWidth: 121,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/mLGrHvf17TaprE2LO1GYqf0Vg.png?width=121&height=121",
												},
											},
											RlMihXU8D: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 60 + 280.8 + 388 + 14,
													),
													pixelHeight: 121,
													pixelWidth: 121,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/mLGrHvf17TaprE2LO1GYqf0Vg.png?width=121&height=121",
												},
											},
											yLsgqhpiR: {
												background: {
													alt: "",
													fit: "stretch",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															(((componentViewport?.height || 639) - 60) *
																0.9983 *
																0.46020761245674763 -
																92) +
															20,
													),
													pixelHeight: 121,
													pixelWidth: 121,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/mLGrHvf17TaprE2LO1GYqf0Vg.png?width=121&height=121",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qhrm3f"}
									data-framer-name={
										"FOMO thrives on comparison. Set a timer for your next check-in and then shift your focus to something that matters to you today."
									}
									fonts={["GF;Poppins-300"]}
									layoutDependency={layoutDependency}
									layoutId={"RVt08Gp32"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											b268i2dTX: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "13px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Jen, when FOMO hits, pause and jot down 3 wins from your day (even small ones)."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											HHXGrB9Qq: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Glad I could help, I\u2019m here anytime you need me."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											onIQ6cqVJ: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Jen, when FOMO hits, pause and jot down 3 wins from your day (even small ones)."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											oZDuSScXV: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Glad I could help, I\u2019m here anytime you need me."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											RlMihXU8D: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "13px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Glad I could help, I\u2019m here anytime you need me."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											yLsgqhpiR: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
															}}
														>
															{
																"Glad I could help, I\u2019m here anytime you need me."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
												"--framer-font-family":
													'"Poppins", "Poppins Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-font-weight": "300",
												"--framer-letter-spacing": "-0.03em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35)))",
											}}
                                            className="responsive-text"
										>
											{
												"Jen, when FOMO hits, pause and jot down 3 wins from your day (even small ones)."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</MotionDivWithFX>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation4}
								__framer__exit={animation6}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-4u1tjr"}
								data-border={true}
								data-framer-name={"problem pill"}
								layoutDependency={layoutDependency}
								layoutId={"mmNisRHnl"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(0, 0, 0, 0.7)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgba(0, 0, 0, 0.8)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									boxShadow: "0px 0px 13px 0px rgba(0, 0, 0, 0.07)",
								}}
								variants={{
									RlMihXU8D: {
										borderBottomLeftRadius: 14,
										borderBottomRightRadius: 14,
										borderTopLeftRadius: 14,
										borderTopRightRadius: 14,
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-hz98v4"}
									data-framer-name={
										"I get so anxious scrolling on social media\u2026like I\u2019m missing out all the time."
									}
									fonts={["GF;Poppins-300"]}
									layoutDependency={layoutDependency}
									layoutId={"lYrdApf3T"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											b268i2dTX: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "13px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
                                                            className="responsive-text"
														>
															{
																"I get so anxious scrolling on social media\u2026like I\u2019m missing out all the time."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											HHXGrB9Qq: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
														>
															{
																"Ummm, I\u2019m seriously glad I could get that off my chest, Thanks Chad."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											onIQ6cqVJ: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
														>
															{
																"I get so anxious scrolling on social media\u2026like I\u2019m missing out all the time."
															}
														</motion.p>
													</React.Fragment>
												),
											},
											oZDuSScXV: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
														>
															{
																"Ummm, I\u2019m seriously glad I could get that off my chest, Thanks Chad."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											RlMihXU8D: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "13px",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
														>
															{
																"Ummm, I\u2019m seriously glad I could get that off my chest, Thanks Chad."
															}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["GF;Poppins-regular"],
											},
											yLsgqhpiR: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "24px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.03em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
															}}
														>
															{
																"Ummm, I\u2019m seriously glad I could get that off my chest, Thanks Chad."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
												"--framer-font-family":
													'"Poppins", "Poppins Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-font-weight": "300",
												"--framer-letter-spacing": "-0.03em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
											}}
                                            className="responsive-text"
										>
											{
												"I get so anxious scrolling on social media\u2026like I\u2019m missing out all the time."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</MotionDivWithFX>
							{isDisplayed() && (
								<MotionDivWithFX
									__framer__animate={{
										transition: transition5,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation4}
									__framer__exit={animation7}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-62fyyt"}
									data-framer-name={"black chat"}
									layoutDependency={layoutDependency}
									layoutId={"u8HTd2RBq"}
									{...addPropertyOverrides(
										{
											b268i2dTX: {
												__framer__enter: animation8,
												__framer__exit: animation9,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1mukonz"}
										data-framer-name={"Group 1"}
										layoutDependency={layoutDependency}
										layoutId={"y2iID8dmi"}
									>
										<motion.div
											className={"framer-960xoe"}
											data-border={true}
											data-framer-name={"problem pill"}
											layoutDependency={layoutDependency}
											layoutId={"lrUviLQVm"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color": "rgba(0, 0, 0, 0.7)",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor: "rgba(0, 0, 0, 0.8)",
												borderBottomLeftRadius: 24,
												borderBottomRightRadius: 24,
												borderTopLeftRadius: 24,
												borderTopRightRadius: 24,
												boxShadow: "0px 0px 13px 0px rgba(0, 0, 0, 0.07)",
											}}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-u3gpvj"}
												data-framer-name={
													"That\u2019s actually really helpful. I\u2019ll try that and see if it takes the pressure off."
												}
												fonts={["GF;Poppins-300"]}
												layoutDependency={layoutDependency}
												layoutId={"H6OiSlYDe"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"center"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														b268i2dTX: {
															children: (
																<React.Fragment>
																	<motion.p
																		style={{
																			"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																			"--framer-font-family":
																				'"Poppins", "Poppins Placeholder", sans-serif',
																			"--framer-font-size": "13px",
																			"--framer-font-weight": "300",
																			"--framer-letter-spacing": "-0.03em",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
																		}}
                                                                        className="responsive-text"
																	>
																		{
																			"That\u2019s actually really helpful. I\u2019ll try that and see if it takes the pressure off."
																		}
																	</motion.p>
																</React.Fragment>
															),
														},
														onIQ6cqVJ: {
															children: (
																<React.Fragment>
																	<motion.p
																		style={{
																			"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
																			"--framer-font-family":
																				'"Poppins", "Poppins Placeholder", sans-serif',
																			"--framer-font-size": "20px",
																			"--framer-font-weight": "300",
																			"--framer-letter-spacing": "-0.03em",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
																		}}
                                                                        className="responsive-text"
																	>
																		{
																			"That\u2019s actually really helpful. I\u2019ll try that and see if it takes the pressure off."
																		}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7UG9wcGlucy0zMDA=",
															"--framer-font-family":
																'"Poppins", "Poppins Placeholder", sans-serif',
															"--framer-font-size": "24px",
															"--framer-font-weight": "300",
															"--framer-letter-spacing": "-0.03em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-f087042b-d073-4748-a812-d40ebb0748d1, rgb(255, 255, 255)))",
														}}
                                                        className="responsive-text"
													>
														{
															"That\u2019s actually really helpful. I\u2019ll try that and see if it takes the pressure off."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</MotionDivWithFX>
							)}
							{isDisplayed1() && (
								<ImageWithFX
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 398,
										intrinsicWidth: 1501,
										pixelHeight: 334,
										pixelWidth: 1439,
										src: "https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334",
										srcSet:
											"https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=512&width=1439&height=334 512w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=1024&width=1439&height=334 1024w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334 1439w",
									}}
									className={"framer-fzjzz3"}
									data-framer-name={"Audio player"}
									layoutDependency={layoutDependency}
									layoutId={"XTejfc0AS"}
									{...addPropertyOverrides(
										{
											HHXGrB9Qq: {
												__framer__animate: {
													transition: transition4,
												},
												__framer__animateOnce: true,
												__framer__enter: animation10,
												__framer__exit: animation11,
												__framer__styleAppearEffectEnabled: true,
												__framer__threshold: 0.5,
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 398,
													intrinsicWidth: 1501,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															((componentViewport?.height || 639) - 60) *
																0.9983 -
															141,
													),
													pixelHeight: 334,
													pixelWidth: 1439,
													sizes: "453px",
													src: "https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334",
													srcSet:
														"https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=512&width=1439&height=334 512w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=1024&width=1439&height=334 1024w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334 1439w",
												},
											},
											oZDuSScXV: {
												__framer__animate: {
													transition: transition4,
												},
												__framer__animateOnce: true,
												__framer__enter: animation10,
												__framer__exit: animation11,
												__framer__styleAppearEffectEnabled: true,
												__framer__threshold: 0.5,
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 398,
													intrinsicWidth: 1501,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															308.8 +
															578 -
															138,
													),
													pixelHeight: 334,
													pixelWidth: 1439,
													sizes: "431px",
													src: "https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334",
													srcSet:
														"https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=512&width=1439&height=334 512w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=1024&width=1439&height=334 1024w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334 1439w",
												},
											},
											RlMihXU8D: {
												__framer__animate: {
													transition: transition4,
												},
												__framer__animateOnce: true,
												__framer__enter: animation10,
												__framer__exit: animation11,
												__framer__styleAppearEffectEnabled: true,
												__framer__threshold: 0.5,
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 398,
													intrinsicWidth: 1501,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 60 + 280.8 + 578 - 89,
													),
													pixelHeight: 334,
													pixelWidth: 1439,
													sizes: "295px",
													src: "https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334",
													srcSet:
														"https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=512&width=1439&height=334 512w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=1024&width=1439&height=334 1024w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334 1439w",
												},
											},
											yLsgqhpiR: {
												__framer__animate: {
													transition: transition4,
												},
												__framer__animateOnce: true,
												__framer__enter: animation10,
												__framer__exit: animation11,
												__framer__styleAppearEffectEnabled: true,
												__framer__threshold: 0.5,
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 398,
													intrinsicWidth: 1501,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															60 +
															((componentViewport?.height || 639) - 60) *
																0.9983 -
															147,
													),
													pixelHeight: 334,
													pixelWidth: 1439,
													sizes: `calc((${componentViewport?.width || "100vw"} - 120px) * 0.4344)`,
													src: "https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334",
													srcSet:
														"https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=512&width=1439&height=334 512w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?scale-down-to=1024&width=1439&height=334 1024w,https://framerusercontent.com/images/JzOl1iwQNcS0o6egTgvbGLJhs.png?width=1439&height=334 1439w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-0COZ1.framer-9o9fex, .framer-0COZ1 .framer-9o9fex { display: block; }",
	".framer-0COZ1.framer-1cv53sz { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; height: 639px; justify-content: space-between; overflow: hidden; padding: 60px 60px 0px 60px; position: relative; width: 1280px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0COZ1 .framer-101n4e { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 32%; }",
	".framer-0COZ1 .framer-njv8nm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-0COZ1 .framer-15yuobz { flex: none; height: auto; max-width: 90%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-0COZ1 .framer-1racp9r { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-0COZ1 .framer-15jb400 { flex: none; height: 100%; overflow: hidden; position: relative; width: 68%; }",
	".framer-0COZ1 .framer-1w59wi7 { flex: none; height: 870px; position: absolute; right: 0px; top: 0px; width: 420px; }",
	".framer-0COZ1 .framer-10scqko { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; left: 48px; overflow: visible; padding: 20px; position: absolute; top: 50%; width: 414px; z-index: 1; }",
	".framer-0COZ1 .framer-79gxlc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); position: relative; width: 40px; }",
	".framer-0COZ1 .framer-1qhrm3f, .framer-0COZ1 .framer-hz98v4, .framer-0COZ1 .framer-u3gpvj { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-0COZ1 .framer-4u1tjr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; left: 0px; overflow: hidden; padding: 20px 30px 20px 30px; position: absolute; top: 36px; width: 415px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0COZ1 .framer-62fyyt { bottom: 38px; flex: none; height: 129px; left: 0px; overflow: visible; position: absolute; width: 414px; z-index: 1; }",
	".framer-0COZ1 .framer-1mukonz { flex: none; height: 129px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 414px; }",
	".framer-0COZ1 .framer-960xoe { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; left: 0px; overflow: hidden; padding: 20px 30px 20px 30px; position: absolute; top: 0px; width: 414px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0COZ1 .framer-fzjzz3 { bottom: 30px; flex: none; height: 117px; overflow: visible; position: absolute; right: 0px; width: 504px; }",
	".framer-0COZ1.framer-v-1bpg8e1.framer-1cv53sz, .framer-0COZ1.framer-v-2lwrq0.framer-1cv53sz { width: 1120px; }",
	".framer-0COZ1.framer-v-1bpg8e1 .framer-10scqko { left: 19px; }",
	".framer-0COZ1.framer-v-wuo9a7.framer-1cv53sz { align-content: center; align-items: center; flex-direction: column; gap: 40px; height: min-content; justify-content: center; padding: 60px 30px 0px 30px; width: 760px; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-101n4e, .framer-0COZ1.framer-v-1232g0g .framer-101n4e { height: min-content; width: 100%; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-15jb400 { height: 578px; width: 700px; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-10scqko { left: 30px; width: 353px; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-4u1tjr { top: 58px; width: 354px; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-62fyyt { bottom: 58px; height: 112px; width: 354px; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-1mukonz { height: 100%; width: 100%; }",
	".framer-0COZ1.framer-v-wuo9a7 .framer-960xoe { width: 353px; }",
	".framer-0COZ1.framer-v-1232g0g.framer-1cv53sz { align-content: center; align-items: center; flex-direction: column; gap: 40px; height: min-content; justify-content: center; padding: 60px 20px 0px 20px; width: 350px; }",
	".framer-0COZ1.framer-v-1232g0g .framer-15jb400 { height: 607px; width: 310px; }",
	".framer-0COZ1.framer-v-1232g0g .framer-1w59wi7 { height: 701px; width: 100%; }",
	".framer-0COZ1.framer-v-1232g0g .framer-10scqko { left: 30px; top: 76%; width: min-content; }",
	".framer-0COZ1.framer-v-1232g0g .framer-79gxlc { height: var(--framer-aspect-ratio-supported, 30px); width: 30px; }",
	".framer-0COZ1.framer-v-1232g0g .framer-1qhrm3f { flex: none; width: 194px; }",
	".framer-0COZ1.framer-v-1232g0g .framer-4u1tjr { bottom: 212px; top: unset; width: 92%; }",
	".framer-0COZ1.framer-v-1232g0g .framer-62fyyt { align-content: center; align-items: center; bottom: 5px; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; width: 94%; }",
	".framer-0COZ1.framer-v-1232g0g .framer-1mukonz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: unset; padding: 0px; position: relative; top: unset; width: 100%; }",
	".framer-0COZ1.framer-v-1232g0g .framer-960xoe { left: unset; padding: 20px; position: relative; top: unset; width: 100%; }",
	".framer-0COZ1.framer-v-h404o6 .framer-101n4e, .framer-0COZ1.framer-v-2lwrq0 .framer-101n4e { order: 1; }",
	".framer-0COZ1.framer-v-h404o6 .framer-15jb400, .framer-0COZ1.framer-v-2lwrq0 .framer-15jb400 { order: 0; }",
	".framer-0COZ1.framer-v-h404o6 .framer-1w59wi7, .framer-0COZ1.framer-v-2lwrq0 .framer-1w59wi7, .framer-0COZ1.framer-v-pse23o .framer-1w59wi7 { left: 0px; right: unset; }",
	".framer-0COZ1.framer-v-h404o6 .framer-10scqko, .framer-0COZ1.framer-v-2lwrq0 .framer-10scqko, .framer-0COZ1.framer-v-pse23o .framer-10scqko { left: unset; right: 20px; top: 46%; }",
	".framer-0COZ1.framer-v-h404o6 .framer-4u1tjr, .framer-0COZ1.framer-v-2lwrq0 .framer-4u1tjr, .framer-0COZ1.framer-v-pse23o .framer-4u1tjr { left: unset; right: 20px; top: 72px; }",
	".framer-0COZ1.framer-v-h404o6 .framer-fzjzz3 { width: 64%; }",
	".framer-0COZ1.framer-v-2lwrq0 .framer-fzjzz3 { bottom: 36px; height: 105px; width: 453px; }",
	".framer-0COZ1.framer-v-pse23o.framer-1cv53sz { align-content: center; align-items: center; flex-direction: column; gap: 68px; height: min-content; justify-content: flex-start; padding: 60px 30px 0px 30px; width: 760px; }",
	".framer-0COZ1.framer-v-pse23o .framer-101n4e, .framer-0COZ1.framer-v-1cvzj6e .framer-101n4e { height: min-content; order: 0; width: 100%; }",
	".framer-0COZ1.framer-v-pse23o .framer-15jb400 { height: 578px; order: 1; width: 100%; }",
	".framer-0COZ1.framer-v-pse23o .framer-fzjzz3 { bottom: 38px; height: 100px; width: 431px; }",
	".framer-0COZ1.framer-v-1cvzj6e.framer-1cv53sz { align-content: center; align-items: center; flex-direction: column; gap: 40px; height: min-content; justify-content: flex-start; padding: 60px 20px 0px 20px; width: 350px; }",
	".framer-0COZ1.framer-v-1cvzj6e .framer-15jb400 { height: 578px; order: 1; overflow: visible; width: 100%; }",
	".framer-0COZ1.framer-v-1cvzj6e .framer-1w59wi7 { height: 670px; left: 3px; right: 3px; width: unset; }",
	".framer-0COZ1.framer-v-1cvzj6e .framer-10scqko { left: unset; padding: 14px; right: 20px; top: 76%; width: 92%; }",
	".framer-0COZ1.framer-v-1cvzj6e .framer-4u1tjr { left: unset; padding: 14px; right: 20px; top: 336px; width: 92%; }",
	".framer-0COZ1.framer-v-1cvzj6e .framer-fzjzz3 { bottom: 20px; height: 69px; right: 5px; width: 295px; }",
	...css2,
	...css,
	'.framer-0COZ1[data-border="true"]::after, .framer-0COZ1 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerLuUHh3uUf = withCSS(Component, css3, "framer-0COZ1");
var stdin_default = FramerLuUHh3uUf;
FramerLuUHh3uUf.displayName = "TEXTING";
FramerLuUHh3uUf.defaultProps = {
	height: 639,
	width: 1280,
};
addPropertyControls(FramerLuUHh3uUf, {
	variant: {
		options: [
			"CRbP10Ds7",
			"GWxnkbO6z",
			"onIQ6cqVJ",
			"b268i2dTX",
			"yLsgqhpiR",
			"HHXGrB9Qq",
			"oZDuSScXV",
			"RlMihXU8D",
		],
		optionTitles: [
			"Desktop",
			"Medium",
			"Tablet",
			"Phone",
			"Male",
			"Male medium",
			"Male tablet",
			"Male phone",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerLuUHh3uUf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLDz8V15vFP-KUEg.woff2",
					weight: "300",
				},
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v23/pxiEyp8kv8JHgFVrFJXUc1NECPY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/VbXXdpBGGoGG4JLpEYUT/c0mmhkFw3pME3KmRhCBR/tXKcvVMmL.js
var TEXTINGFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX2(
	SmartComponentScopedContainer,
);
var cycleOrder2 = ["RwlhYT1Z9", "nePX3L0O3", "iyULrpPGP", "tTGmZRdYk"];
var serializationHash2 = "framer-01Siq";
var variantClassNames2 = {
	iyULrpPGP: "framer-v-7v3tn7",
	nePX3L0O3: "framer-v-z04jn8",
	RwlhYT1Z9: "framer-v-9m3l71",
	tTGmZRdYk: "framer-v-1x1epri",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation12 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition22 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation13 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition22,
	x: 0,
	y: 30,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "RwlhYT1Z9",
	Medium: "nePX3L0O3",
	Phone: "tTGmZRdYk",
	Tablet: "iyULrpPGP",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "RwlhYT1Z9",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "RwlhYT1Z9",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-9m3l71",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"RwlhYT1Z9"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								iyULrpPGP: {
									"data-framer-name": "Tablet",
								},
								nePX3L0O3: {
									"data-framer-name": "Medium",
								},
								tTGmZRdYk: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-jwq37s"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"WgBj9jPPm"}
						>
							<motion2.div
								className={"framer-1rkv5k8"}
								data-framer-name={"Grouped"}
								layoutDependency={layoutDependency}
								layoutId={"n4JkZV9Kb"}
							>
								<ComponentViewportProvider
									height={639}
									width={`min(${componentViewport?.width || "100vw"} - 160px, 1280px)`}
									y={(componentViewport?.y || 0) + 140 + 0 + 0 + 0 + 0 + 0}
									{...addPropertyOverrides2(
										{
											iyULrpPGP: {
												width: `min(${componentViewport?.width || "100vw"} - 60px, 1280px)`,
											},
											nePX3L0O3: {
												width: `min(${componentViewport?.width || "100vw"} - 100px, 1280px)`,
											},
											tTGmZRdYk: {
												width: `min(${componentViewport?.width || "100vw"} - 40px, 1280px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition22,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation12}
										__framer__exit={animation13}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1wne135-container"}
										layoutDependency={layoutDependency}
										layoutId={"seg0M7COn-container"}
										nodeId={"seg0M7COn"}
										rendersWithMotion={true}
										scopeId={"tXKcvVMmL"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "seg0M7COn",
											layoutId: "seg0M7COn",
											style: {
												width: "100%",
											},
											variant: "CRbP10Ds7",
											width: "100%",
											...addPropertyOverrides2(
												{
													iyULrpPGP: {
														variant: "onIQ6cqVJ",
													},
													nePX3L0O3: {
														variant: "GWxnkbO6z",
													},
													tTGmZRdYk: {
														variant: "b268i2dTX",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={639}
									width={`min(${componentViewport?.width || "100vw"} - 160px, 1280px)`}
									y={(componentViewport?.y || 0) + 140 + 0 + 0 + 0 + 0 + 663}
									{...addPropertyOverrides2(
										{
											iyULrpPGP: {
												width: `min(${componentViewport?.width || "100vw"} - 60px, 1280px)`,
											},
											nePX3L0O3: {
												width: `min(${componentViewport?.width || "100vw"} - 100px, 1280px)`,
											},
											tTGmZRdYk: {
												width: `min(${componentViewport?.width || "100vw"} - 40px, 1280px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition22,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation12}
										__framer__exit={animation13}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-19jwae0-container"}
										layoutDependency={layoutDependency}
										layoutId={"btyxmIaKg-container"}
										nodeId={"btyxmIaKg"}
										rendersWithMotion={true}
										scopeId={"tXKcvVMmL"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "btyxmIaKg",
											layoutId: "btyxmIaKg",
											style: {
												width: "100%",
											},
											variant: "yLsgqhpiR",
											width: "100%",
											...addPropertyOverrides2(
												{
													iyULrpPGP: {
														variant: "oZDuSScXV",
													},
													nePX3L0O3: {
														variant: "HHXGrB9Qq",
													},
													tTGmZRdYk: {
														variant: "RlMihXU8D",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-01Siq.framer-vsikwm, .framer-01Siq .framer-vsikwm { display: block; }",
	".framer-01Siq.framer-9m3l71 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 140px 80px 0px 80px; position: relative; width: 1920px; }",
	".framer-01Siq .framer-jwq37s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; max-width: 1280px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-01Siq .framer-1rkv5k8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-01Siq .framer-1wne135-container, .framer-01Siq .framer-19jwae0-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-01Siq.framer-v-z04jn8.framer-9m3l71 { padding: 140px 50px 0px 50px; width: 1120px; }",
	".framer-01Siq.framer-v-7v3tn7.framer-9m3l71 { padding: 140px 30px 0px 30px; width: 200px; }",
	".framer-01Siq.framer-v-1x1epri.framer-9m3l71 { padding: 140px 20px 0px 20px; width: 100%; }",
];
var FramertXKcvVMmL = withCSS2(Component2, css4, "framer-01Siq");
var stdin_default2 = FramertXKcvVMmL;
FramertXKcvVMmL.displayName = "CALL OR TEXT";
FramertXKcvVMmL.defaultProps = {
	height: 1442,
	width: 1920,
};
addPropertyControls2(FramertXKcvVMmL, {
	variant: {
		options: ["RwlhYT1Z9", "nePX3L0O3", "iyULrpPGP", "tTGmZRdYk"],
		optionTitles: ["Desktop", "Medium", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramertXKcvVMmL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TEXTINGFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:call-or-text
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tTGmZRdYk",
	md: "iyULrpPGP",
	lg: "nePX3L0O3",
	"2xl": "RwlhYT1Z9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e174c9286f577d890cd3ebd3f2bbe1795257a26f52465d7e4a58bd10905a6285"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CallOrTextFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e174c9286f577d890cd3ebd3f2bbe1795257a26f52465d7e4a58bd10905a6285"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var call_or_text_default = ComponentWithRoot;
export { call_or_text_default as default };
