// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e174c9286f577d89 "Innermost AI (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
	routes,
} from "./chunks/chunk-RDT2PSA6.js";

// virtual:faq-section
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/s7DZQHiiEfIVQgnOTknn/EHcQtGUeL3H46fx9t5Ie/BNoUhUvmu.js
import { jsx as _jsx5, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider3,
	ControlType as ControlType4,
	cx as cx3,
	getFonts as getFonts3,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React5 from "react";
import { useRef as useRef4 } from "react";

// /:https://framerusercontent.com/modules/siz5zDVSNQ7VtyUmzJtt/N10r1KGA7Vv47q7gjiqT/xzaMTr1UK.js
import { jsx as _jsx4, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider as ComponentViewportProvider2,
	cx as cx2,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/my9sF4GB0w9b6FYMsP82/2hgtfG4pTYLKOrrDByqQ/Dvy9p0TYT.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import * as React2 from "react";
import { useState, useEffect, useRef } from "react";
import {
	addPropertyControls,
	ControlType as ControlType2,
	RenderTarget,
} from "unframer";

// /:https://framer.com/m/framer/icon-nullstate.js@0.7.0
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
var containerStyles = {
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(149, 149, 149, 0.1)",
	border: "1px dashed rgba(149, 149, 149, 0.15)",
	color: "#a5a5a5",
	flexDirection: "column",
};
var NullState = /* @__PURE__ */ React.forwardRef((_, ref) => {
	return <div style={emptyStateStyle} ref={ref} />;
});

// /:https://framer.com/m/feather-icons/home.js@0.0.29
var r;
var s = (o) => {
	if (!r) {
		const n = o.forwardRef(
			({ color: t = "currentColor", size: e = 24, ...i }, l) =>
				o.createElement(
					"svg",
					{
						ref: l,
						xmlns: "http://www.w3.org/2000/svg",
						width: e,
						height: e,
						viewBox: "0 0 24 24",
						fill: "none",
						stroke: t,
						strokeWidth: "2",
						strokeLinecap: "round",
						strokeLinejoin: "round",
						...i,
					},
					o.createElement("path", {
						d: "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
					}),
					o.createElement("polyline", {
						points: "9 22 9 12 15 12 15 22",
					}),
				),
		);
		(n.displayName = "Home"), (r = n);
	}
	return r;
};

// /:https://framerusercontent.com/modules/Ma20hU0GGRxLxZphbywl/OSpwWF91FHPVFyQJjMHt/utils.js
import { useMemo } from "react";
import { ControlType } from "unframer";
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseDown: {
		type: ControlType.EventHandler,
	},
	onMouseUp: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var findByArray = (arr, search) =>
	arr.find((a) => a.toLowerCase().includes(search));
function useIconSelection(
	iconKeys2,
	selectByList,
	iconSearch = "",
	iconSelection,
	lowercaseIconKeyPairs2,
) {
	const iconSearchResult = useMemo(() => {
		if (
			iconSearch == null ||
			(iconSearch === null || iconSearch === void 0
				? void 0
				: iconSearch.length) === 0
		)
			return null;
		const iconSearchTerm = iconSearch.toLowerCase().replace(/-|\s/g, "");
		var _iconSearchTerm;
		const searchResult =
			(_iconSearchTerm = lowercaseIconKeyPairs2[iconSearchTerm]) !== null &&
			_iconSearchTerm !== void 0
				? _iconSearchTerm
				: findByArray(iconKeys2, iconSearchTerm);
		return searchResult;
	}, [iconSelection, iconSearch]);
	const name = selectByList ? iconSelection : iconSearchResult;
	return name;
}

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
var iconKeys = [
	"activity",
	"airplay",
	"alert-circle",
	"alert-octagon",
	"alert-triangle",
	"align-center",
	"align-justify",
	"align-left",
	"align-right",
	"anchor",
	"aperture",
	"archive",
	"arrow-down",
	"arrow-down-circle",
	"arrow-down-left",
	"arrow-down-right",
	"arrow-left",
	"arrow-left-circle",
	"arrow-right",
	"arrow-right-circle",
	"arrow-up",
	"arrow-up-circle",
	"arrow-up-left",
	"arrow-up-right",
	"at-sign",
	"award",
	"bar-chart",
	"bar-chart-2",
	"battery",
	"battery-charging",
	"bell",
	"bell-off",
	"bluetooth",
	"bold",
	"book",
	"book-open",
	"bookmark",
	"box",
	"briefcase",
	"calendar",
	"camera",
	"camera-off",
	"cast",
	"check",
	"check-circle",
	"check-square",
	"chevron-down",
	"chevron-left",
	"chevron-right",
	"chevron-up",
	"chevrons-down",
	"chevrons-left",
	"chevrons-right",
	"chevrons-up",
	"chrome",
	"circle",
	"clipboard",
	"clock",
	"cloud",
	"cloud-drizzle",
	"cloud-lightning",
	"cloud-off",
	"cloud-rain",
	"cloud-snow",
	"code",
	"codepen",
	"codesandbox",
	"coffee",
	"columns",
	"command",
	"compass",
	"copy",
	"corner-down-left",
	"corner-down-right",
	"corner-left-down",
	"corner-left-up",
	"corner-right-down",
	"corner-right-up",
	"corner-up-left",
	"corner-up-right",
	"cpu",
	"credit-card",
	"crop",
	"crosshair",
	"database",
	"delete",
	"disc",
	"divide",
	"divide-circle",
	"divide-square",
	"dollar-sign",
	"download",
	"download-cloud",
	"dribbble",
	"droplet",
	"edit",
	"edit-2",
	"edit-3",
	"external-link",
	"eye",
	"eye-off",
	"facebook",
	"fast-forward",
	"feather",
	"figma",
	"file",
	"file-minus",
	"file-plus",
	"file-text",
	"film",
	"filter",
	"flag",
	"folder",
	"folder-minus",
	"folder-plus",
	"framer",
	"frown",
	"gift",
	"git-branch",
	"git-commit",
	"git-merge",
	"git-pull-request",
	"github",
	"gitlab",
	"globe",
	"grid",
	"hard-drive",
	"hash",
	"headphones",
	"heart",
	"help-circle",
	"hexagon",
	"home",
	"image",
	"inbox",
	"info",
	"instagram",
	"italic",
	"key",
	"layers",
	"layout",
	"life-buoy",
	"link",
	"link-2",
	"linkedin",
	"list",
	"loader",
	"lock",
	"log-in",
	"log-out",
	"mail",
	"map",
	"map-pin",
	"maximize",
	"maximize-2",
	"meh",
	"menu",
	"message-circle",
	"message-square",
	"mic",
	"mic-off",
	"minimize",
	"minimize-2",
	"minus",
	"minus-circle",
	"minus-square",
	"monitor",
	"moon",
	"more-horizontal",
	"more-vertical",
	"mouse-pointer",
	"move",
	"music",
	"navigation",
	"navigation-2",
	"octagon",
	"package",
	"paperclip",
	"pause",
	"pause-circle",
	"pen-tool",
	"percent",
	"phone",
	"phone-call",
	"phone-forwarded",
	"phone-incoming",
	"phone-missed",
	"phone-off",
	"phone-outgoing",
	"pie-chart",
	"play",
	"play-circle",
	"plus",
	"plus-circle",
	"plus-square",
	"pocket",
	"power",
	"printer",
	"radio",
	"refresh-ccw",
	"refresh-cw",
	"repeat",
	"rewind",
	"rotate-ccw",
	"rotate-cw",
	"rss",
	"save",
	"scissors",
	"search",
	"send",
	"server",
	"settings",
	"share",
	"share-2",
	"shield",
	"shield-off",
	"shopping-bag",
	"shopping-cart",
	"shuffle",
	"sidebar",
	"skip-back",
	"skip-forward",
	"slack",
	"slash",
	"sliders",
	"smartphone",
	"smile",
	"speaker",
	"square",
	"star",
	"stop-circle",
	"sun",
	"sunrise",
	"sunset",
	"tablet",
	"tag",
	"target",
	"terminal",
	"thermometer",
	"thumbs-down",
	"thumbs-up",
	"toggle-left",
	"toggle-right",
	"tool",
	"trash",
	"trash-2",
	"trello",
	"trending-down",
	"trending-up",
	"triangle",
	"truck",
	"tv",
	"twitch",
	"twitter",
	"type",
	"umbrella",
	"underline",
	"unlock",
	"upload",
	"upload-cloud",
	"user",
	"user-check",
	"user-minus",
	"user-plus",
	"user-x",
	"users",
	"video",
	"video-off",
	"voicemail",
	"volume",
	"volume-1",
	"volume-2",
	"volume-x",
	"watch",
	"wifi",
	"wifi-off",
	"wind",
	"x",
	"x-circle",
	"x-octagon",
	"x-square",
	"youtube",
	"zap",
	"zap-off",
	"zoom-in",
	"zoom-out",
];
var moduleBaseUrl = "https://framer.com/m/feather-icons/";
var uppercaseIconKeys = iconKeys.map(
	(name) => name.charAt(0).toUpperCase() + name.slice(1),
);
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? s(React2) : null,
	);
	async function importModule() {
		let active = true;
		try {
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@0.0.29`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (active) setSelectedIcon(module.default(React2));
		} catch (e) {
			console.log(e);
			if (active) setSelectedIcon(null);
		}
		return () => {
			active = false;
		};
	}
	useEffect(() => {
		importModule();
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<SelectedIcon
					style={{
						width: "100%",
						height: "100%",
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					color={color}
				/>
			) : (
				emptyState
			)}
		</div>
	);
}
Icon.displayName = "Feather";
Icon.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "home",
	iconSearch: "Home",
	color: "#66F",
	selectByList: true,
	mirrored: false,
};
addPropertyControls(Icon, {
	selectByList: {
		type: ControlType2.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType2.Enum,
		options: iconKeys,
		optionTitles: uppercaseIconKeys,
		defaultValue: Icon.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Feather site](https://feathericons.com/)",
	},
	iconSearch: {
		type: ControlType2.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	mirrored: {
		type: ControlType2.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon.defaultProps.mirrored,
	},
	color: {
		type: ControlType2.Color,
		title: "Color",
		defaultValue: Icon.defaultProps.color,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/XV3tLlJcWIzThRrvFhaT/hFZToKoVa5mu4j59GVpU/BKN3cZENt.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Poppins-regular",
	"GF;Poppins-700",
	"GF;Poppins-700italic",
	"GF;Poppins-italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiEyp8kv8JHgFVrFJXUc1NECPY.woff2",
				weight: "400",
			},
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLCz7V15vFP-KUEg.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiDyp8kv8JHgFVrJJLmy15lFd2PQEhcqw.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiGyp8kv8JHgFVrJJLecnFBGPaTSQ.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	'.framer-QfGZP .framer-styles-preset-uknhya:not(.rich-text-wrapper), .framer-QfGZP .framer-styles-preset-uknhya.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-QfGZP .framer-styles-preset-uknhya:not(.rich-text-wrapper), .framer-QfGZP .framer-styles-preset-uknhya.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 19px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-QfGZP .framer-styles-preset-uknhya:not(.rich-text-wrapper), .framer-QfGZP .framer-styles-preset-uknhya.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-QfGZP";

// /:https://framerusercontent.com/modules/PZu6sU61mEgrlO1KpO3h/lYrK48jqrI8TDfKYwwtA/Q4oX12qZZ.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Poppins-500",
	"GF;Poppins-700",
	"GF;Poppins-700italic",
	"GF;Poppins-500italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLGT9V15vFP-KUEg.woff2",
				weight: "500",
			},
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLCz7V15vFP-KUEg.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiDyp8kv8JHgFVrJJLmy15lFd2PQEhcqw.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiDyp8kv8JHgFVrJJLmg1hlFd2PQEhcqw.woff2",
				weight: "500",
			},
		],
	},
];
var css4 = [
	'.framer-cUzDu .framer-styles-preset-kd5aam:not(.rich-text-wrapper), .framer-cUzDu .framer-styles-preset-kd5aam.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-cUzDu .framer-styles-preset-kd5aam:not(.rich-text-wrapper), .framer-cUzDu .framer-styles-preset-kd5aam.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-cUzDu .framer-styles-preset-kd5aam:not(.rich-text-wrapper), .framer-cUzDu .framer-styles-preset-kd5aam.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #242423; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className4 = "framer-cUzDu";

// /:https://framerusercontent.com/modules/my9sF4GB0w9b6FYMsP82/2hgtfG4pTYLKOrrDByqQ/Dvy9p0TYT.js
var FeatherFonts = getFonts(Icon);
var enabledGestures = {
	uOtGq34Lc: {
		hover: true,
	},
};
var cycleOrder = ["uOtGq34Lc", "xCMg5qk1J"];
var serializationHash = "framer-UGSrs";
var variantClassNames = {
	uOtGq34Lc: "framer-v-1yt6zlf",
	xCMg5qk1J: "framer-v-xrj8yi",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React3.Fragment);
var humanReadableVariantMap = {
	Close: "uOtGq34Lc",
	Open: "xCMg5qk1J",
};
var getProps = ({
	click,
	description,
	height,
	id,
	question,
	width,
	...props
}) => {
	return {
		...props,
		h8iGjYmBY: question ?? props.h8iGjYmBY ?? "Question",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uOtGq34Lc",
		wQl2D9PqT: click ?? props.wQl2D9PqT,
		YgvPXMWsF: description ?? props.YgvPXMWsF ?? "Description",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		h8iGjYmBY,
		YgvPXMWsF,
		wQl2D9PqT,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uOtGq34Lc",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaphu9o6t = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wQl2D9PqT) {
			const res = await wQl2D9PqT(...args);
			if (res === false) return false;
		}
		setVariant("xCMg5qk1J");
	});
	const onTap1eoltyq = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wQl2D9PqT) {
			const res = await wQl2D9PqT(...args);
			if (res === false) return false;
		}
		setVariant("uOtGq34Lc");
	});
	const sharedStyleClassNames = [className4, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "xCMg5qk1J") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1yt6zlf",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"uOtGq34Lc"}
						onTap={onTaphu9o6t}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-466f412f-31e4-4f7f-a7e6-91a69b113f31, rgba(1, 1, 1, 0))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-7cbc8809-805f-42b8-a101-1dbda095b6b0, rgb(247, 245, 242))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						variants={{
							xCMg5qk1J: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
						}}
						{...addPropertyOverrides(
							{
								"uOtGq34Lc-hover": {
									"data-framer-name": void 0,
								},
								xCMg5qk1J: {
									"data-framer-name": "Open",
									onTap: onTap1eoltyq,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1w69eun"}
							data-framer-name={"Accordion content"}
							layoutDependency={layoutDependency}
							layoutId={"gzKKf5fPF"}
						>
							<motion.div
								className={"framer-1ejnbzp"}
								data-framer-name={"Heading"}
								layoutDependency={layoutDependency}
								layoutId={"wjqVQOWKn"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-eewxmc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"WSYW98t_X"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={h8iGjYmBY}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion.p
											className={"framer-styles-preset-kd5aam"}
											data-styles-preset={"Q4oX12qZZ"}
										>
											{"Question"}
										</motion.p>
									</React3.Fragment>
								</RichText>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-hezk94-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"eFAc0gYHu-container"}
										nodeId={"eFAc0gYHu"}
										rendersWithMotion={true}
										scopeId={"Dvy9p0TYT"}
										style={{
											rotate: 45,
										}}
										variants={{
											xCMg5qk1J: {
												rotate: 180,
											},
										}}
									>
										<Icon
											color={
												"var(--token-b96ed00f-f1b0-47f1-85a2-09f5e52d4710, rgb(36, 36, 35))"
											}
											height={"100%"}
											iconSearch={"Home"}
											iconSelection={"x"}
											id={"eFAc0gYHu"}
											layoutId={"eFAc0gYHu"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1924e69"}
									data-framer-name={"Description"}
									layoutDependency={layoutDependency}
									layoutId={"oMHh91RiR"}
								>
									{isDisplayed() && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-u7bj16"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Xg28CbGp7"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={YgvPXMWsF}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React3.Fragment>
												<motion.p
													className={"framer-styles-preset-uknhya"}
													data-styles-preset={"BKN3cZENt"}
												>
													{"Description"}
												</motion.p>
											</React3.Fragment>
										</RichText>
									)}
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UGSrs.framer-zmqu5n, .framer-UGSrs .framer-zmqu5n { display: block; }",
	".framer-UGSrs.framer-1yt6zlf { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 18px 15px 24px 15px; position: relative; width: 854px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UGSrs .framer-1w69eun { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 94%; }",
	".framer-UGSrs .framer-1ejnbzp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-UGSrs .framer-eewxmc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-UGSrs .framer-hezk94-container { flex: none; height: 14px; position: relative; width: 14px; }",
	".framer-UGSrs .framer-1924e69 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 200px; overflow: visible; padding: 0px 30px 0px 0px; position: relative; width: 100%; }",
	".framer-UGSrs .framer-u7bj16 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-UGSrs.framer-v-xrj8yi.framer-1yt6zlf { padding: 35px 15px 35px 15px; }",
	".framer-UGSrs.framer-v-xrj8yi .framer-1924e69 { min-height: unset; }",
	...css4,
	...css3,
	'.framer-UGSrs[data-border="true"]::after, .framer-UGSrs [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerDvy9p0TYT = withCSS(Component, css5, "framer-UGSrs");
var stdin_default = FramerDvy9p0TYT;
FramerDvy9p0TYT.displayName = "FAQ/Accordion Item";
FramerDvy9p0TYT.defaultProps = {
	height: 71,
	width: 854,
};
addPropertyControls2(FramerDvy9p0TYT, {
	variant: {
		options: ["uOtGq34Lc", "xCMg5qk1J"],
		optionTitles: ["Close", "Open"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	h8iGjYmBY: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question",
		type: ControlType3.String,
	},
	YgvPXMWsF: {
		defaultValue: "Description",
		displayTextArea: true,
		title: "Description",
		type: ControlType3.String,
	},
	wQl2D9PqT: {
		title: "Click",
		type: ControlType3.EventHandler,
	},
});
addFonts(
	FramerDvy9p0TYT,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/siz5zDVSNQ7VtyUmzJtt/N10r1KGA7Vv47q7gjiqT/xzaMTr1UK.js
var FAQAccordionItemFonts = getFonts2(stdin_default);
var serializationHash2 = "framer-HYOHM";
var variantClassNames2 = {
	VxX63v3d7: "framer-v-1sj5zx7",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React4.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "VxX63v3d7",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1sj5zx7",
							className5,
							classNames,
						)}
						data-framer-name={"Accordion Collapsed"}
						layoutDependency={layoutDependency}
						layoutId={"VxX63v3d7"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider2
							height={71}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 431) - 0 - 403) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer2
								className={"framer-1aupeqa-container"}
								layoutDependency={layoutDependency}
								layoutId={"HjSp0oLm1-container"}
								nodeId={"HjSp0oLm1"}
								rendersWithMotion={true}
								scopeId={"xzaMTr1UK"}
							>
								{_jsx4(stdin_default, {
									h8iGjYmBY:
										"What kinds of challenges can Innermost AI guides help me with?",
									height: "100%",
									id: "HjSp0oLm1",
									layoutId: "HjSp0oLm1",
									style: {
										width: "100%",
									},
									variant: "uOtGq34Lc",
									width: "100%",
									YgvPXMWsF:
										"Our AI guides can support you through a wide range of life challenges \u2014 from building healthier habits and finding motivation, to managing stress, navigating difficult emotions, and gaining clarity on personal goals. Along the way, they\u2019ll offer tips, resources, reflections, and personalized suggestions designed to fit your unique journey.\u2028",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={71}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 431) - 0 - 403) / 2 + 71 + 12)
							}
						>
							<SmartComponentScopedContainer2
								className={"framer-9v7ttb-container"}
								layoutDependency={layoutDependency}
								layoutId={"TELnkkml7-container"}
								nodeId={"TELnkkml7"}
								rendersWithMotion={true}
								scopeId={"xzaMTr1UK"}
							>
								{_jsx4(stdin_default, {
									h8iGjYmBY: "How is my privacy protected?",
									height: "100%",
									id: "TELnkkml7",
									layoutId: "TELnkkml7",
									style: {
										width: "100%",
									},
									variant: "uOtGq34Lc",
									width: "100%",
									YgvPXMWsF:
										"Your privacy is our top priority. Everything you share with Innermost is encrypted, stored securely, and never sold to third parties. Your data belongs to you \u2014 always. Our AI guides are designed to support your growth without judgment, and your reflections remain private unless you choose to share them.\u2028",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={71}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 431) - 0 - 403) / 2 + 142 + 24)
							}
						>
							<SmartComponentScopedContainer2
								className={"framer-m6xqs2-container"}
								layoutDependency={layoutDependency}
								layoutId={"mA4ZPYKOG-container"}
								nodeId={"mA4ZPYKOG"}
								rendersWithMotion={true}
								scopeId={"xzaMTr1UK"}
							>
								{_jsx4(stdin_default, {
									h8iGjYmBY:
										"How is Innermost different from other self-help tools?",
									height: "100%",
									id: "mA4ZPYKOG",
									layoutId: "mA4ZPYKOG",
									style: {
										width: "100%",
									},
									variant: "uOtGq34Lc",
									width: "100%",
									YgvPXMWsF:
										"Unlike traditional self-help apps, Innermost isn\u2019t about generic advice or one-size-fits-all content. It\u2019s a dynamic, AI-powered companion that adapts to your needs, learning from your reflections and tailoring guidance in real time. Think of it as a personal growth feed \u2014 curated just for you \u2014 where insights, prompts, and support are delivered in a way that feels human, conversational, and relevant.\u2028",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={71}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 431) - 0 - 403) / 2 + 213 + 36)
							}
						>
							<SmartComponentScopedContainer2
								className={"framer-1k8qrmc-container"}
								layoutDependency={layoutDependency}
								layoutId={"SHouGqCyu-container"}
								nodeId={"SHouGqCyu"}
								rendersWithMotion={true}
								scopeId={"xzaMTr1UK"}
							>
								{_jsx4(stdin_default, {
									h8iGjYmBY: "Can I customize the type of guidance I receive?",
									height: "100%",
									id: "SHouGqCyu",
									layoutId: "SHouGqCyu",
									style: {
										width: "100%",
									},
									variant: "uOtGq34Lc",
									width: "100%",
									YgvPXMWsF:
										"Yes. You can choose the focus areas that matter most to you \u2014 whether it\u2019s stress management, self-confidence, motivation, or emotional clarity. Over time, your AI guide learns your preferences and adapts, ensuring your experience feels truly personal.\u2028",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={71}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 431) - 0 - 403) / 2 + 284 + 48)
							}
						>
							<SmartComponentScopedContainer2
								className={"framer-psnxf9-container"}
								layoutDependency={layoutDependency}
								layoutId={"nmUNm2Uv3-container"}
								nodeId={"nmUNm2Uv3"}
								rendersWithMotion={true}
								scopeId={"xzaMTr1UK"}
							>
								{_jsx4(stdin_default, {
									h8iGjYmBY: "Can this replace therapy or professional help?",
									height: "100%",
									id: "nmUNm2Uv3",
									layoutId: "nmUNm2Uv3",
									style: {
										width: "100%",
									},
									variant: "uOtGq34Lc",
									width: "100%",
									YgvPXMWsF:
										"No. Innermost is designed to complement \u2014 not replace \u2014 therapy, coaching, or professional support. It\u2019s a safe space for reflection, guidance, and growth between sessions or outside of therapy altogether. While Innermost can help you gain insights and build healthy habits, it is not a substitute for professional mental health care.",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HYOHM.framer-15qup7t, .framer-HYOHM .framer-15qup7t { display: block; }",
	".framer-HYOHM.framer-1sj5zx7 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 854px; }",
	".framer-HYOHM .framer-1aupeqa-container, .framer-HYOHM .framer-9v7ttb-container, .framer-HYOHM .framer-m6xqs2-container, .framer-HYOHM .framer-1k8qrmc-container, .framer-HYOHM .framer-psnxf9-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerxzaMTr1UK = withCSS2(Component2, css6, "framer-HYOHM");
var stdin_default2 = FramerxzaMTr1UK;
FramerxzaMTr1UK.displayName = "FAQ/Accordion";
FramerxzaMTr1UK.defaultProps = {
	height: 431,
	width: 854,
};
addFonts2(
	FramerxzaMTr1UK,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FAQAccordionItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/s7DZQHiiEfIVQgnOTknn/EHcQtGUeL3H46fx9t5Ie/BNoUhUvmu.js
var RichTextWithFX = withFX(RichText2);
var FAQAccordionFonts = getFonts3(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(
	SmartComponentScopedContainer3,
);
var MotionDivWithFX = withFX(motion3.div);
var cycleOrder2 = ["qF5JknOSk", "D_qG9ecEc", "ISwydG9uT", "sztNLm7tN"];
var serializationHash3 = "framer-vjqxe";
var variantClassNames3 = {
	D_qG9ecEc: "framer-v-1c77scm",
	ISwydG9uT: "framer-v-1neglk7",
	qF5JknOSk: "framer-v-37v1ii",
	sztNLm7tN: "framer-v-b65qgm",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 30,
};
var transition3 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 30,
};
var transition4 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React5.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "qF5JknOSk",
	Medium: "D_qG9ecEc",
	Phone: "sztNLm7tN",
	Tablet: "ISwydG9uT",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "qF5JknOSk",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder2,
		defaultVariant: "qF5JknOSk",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-37v1ii",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"qF5JknOSk"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								D_qG9ecEc: {
									"data-framer-name": "Medium",
								},
								ISwydG9uT: {
									"data-framer-name": "Tablet",
								},
								sztNLm7tN: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-1p323wi"}
							data-framer-name={"FAQ SECTION"}
							layoutDependency={layoutDependency}
							layoutId={"te0d3lyrj"}
						>
							<motion3.div
								className={"framer-8j38sa"}
								data-framer-name={"Section title"}
								layoutDependency={layoutDependency}
								layoutId={"lsbhn8D89"}
							>
								<RichTextWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1bzb0d8"}
									data-framer-name={"FAQ"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"tqZuypSsB"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React5.Fragment>
										<motion3.p
											className={"framer-styles-preset-6f861z"}
											data-styles-preset={"FQIVEzdXc"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"FAQ"}
										</motion3.p>
									</React5.Fragment>
								</RichTextWithFX>
								<motion3.div
									className={"framer-1f4ll8i"}
									data-framer-name={"tagline+title"}
									layoutDependency={layoutDependency}
									layoutId={"rqjcKJgh_"}
								>
									<RichTextWithFX
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-16jtcda"}
										data-framer-name={"Here\u2019s what you should know"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"IpeIiN_SF"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion3.h2
												className={"framer-styles-preset-18v01r2"}
												data-styles-preset={"WFCKJ8ZJ6"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"Here\u2019s what you should know"}
											</motion3.h2>
										</React5.Fragment>
									</RichTextWithFX>
								</motion3.div>
							</motion3.div>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-xoxscl"}
								data-framer-name={"questions"}
								layoutDependency={layoutDependency}
								layoutId={"cyPeDpKok"}
							>
								<ComponentViewportProvider3
									height={431}
									width={`min(min(1280px, ${componentViewport?.width || "100vw"}) - 100px, 800px)`}
									y={
										(componentViewport?.y || 0) +
										(140 +
											((componentViewport?.height || 200) - 280 - 588.6) / 2) +
										0 +
										157.6 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											D_qG9ecEc: {
												width: `min(min(max(${componentViewport?.width || "100vw"}, 1px), ${componentViewport?.width || "100vw"}) - 100px, 800px)`,
											},
											ISwydG9uT: {
												width: `min(min(1280px, ${componentViewport?.width || "100vw"}) - 60px, 800px)`,
											},
											sztNLm7tN: {
												width: `min(min(max(${componentViewport?.width || "100vw"}, 1px), ${componentViewport?.width || "100vw"}) - 40px, 800px)`,
												y:
													(componentViewport?.y || 0) +
													(100 +
														((componentViewport?.height || 200) - 200 - 588.6) /
															2) +
													0 +
													157.6 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-u53yf6-container"}
										layoutDependency={layoutDependency}
										layoutId={"TugcaIGKp-container"}
										nodeId={"TugcaIGKp"}
										rendersWithMotion={true}
										scopeId={"BNoUhUvmu"}
									>
										{_jsx5(stdin_default2, {
											height: "100%",
											id: "TugcaIGKp",
											layoutId: "TugcaIGKp",
											style: {
												maxWidth: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider3>
							</MotionDivWithFX>
						</motion3.div>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vjqxe.framer-1caxvy0, .framer-vjqxe .framer-1caxvy0 { display: block; }",
	".framer-vjqxe.framer-37v1ii { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 140px 0px 140px 0px; position: relative; width: 1920px; }",
	".framer-vjqxe .framer-1p323wi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 1280px; }",
	".framer-vjqxe .framer-8j38sa { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vjqxe .framer-1bzb0d8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-vjqxe .framer-1f4ll8i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 871px; }",
	".framer-vjqxe .framer-16jtcda { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-vjqxe .framer-xoxscl { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 50px 0px 50px; position: relative; width: 100%; }",
	".framer-vjqxe .framer-u53yf6-container { flex: none; height: auto; max-width: 800px; position: relative; width: 100%; }",
	".framer-vjqxe.framer-v-1c77scm.framer-37v1ii { width: 1120px; }",
	".framer-vjqxe.framer-v-1c77scm .framer-1p323wi, .framer-vjqxe.framer-v-b65qgm .framer-1p323wi { flex: 1 0 0px; width: 1px; }",
	".framer-vjqxe.framer-v-1neglk7.framer-37v1ii { width: 200px; }",
	".framer-vjqxe.framer-v-1neglk7 .framer-xoxscl { padding: 0px 30px 0px 30px; }",
	".framer-vjqxe.framer-v-b65qgm.framer-37v1ii { padding: 100px 0px 100px 0px; width: 100%; }",
	".framer-vjqxe.framer-v-b65qgm .framer-1f4ll8i { padding: 0px 20px 0px 20px; width: 100%; }",
	".framer-vjqxe.framer-v-b65qgm .framer-xoxscl { padding: 0px 20px 0px 20px; }",
	...css,
	...css2,
];
var FramerBNoUhUvmu = withCSS3(Component3, css7, "framer-vjqxe");
var stdin_default3 = FramerBNoUhUvmu;
FramerBNoUhUvmu.displayName = "FAQ SECTION";
FramerBNoUhUvmu.defaultProps = {
	height: 868,
	width: 1920,
};
addPropertyControls3(FramerBNoUhUvmu, {
	variant: {
		options: ["qF5JknOSk", "D_qG9ecEc", "ISwydG9uT", "sztNLm7tN"],
		optionTitles: ["Desktop", "Medium", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType4.Enum,
	},
});
addFonts3(
	FramerBNoUhUvmu,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FAQAccordionFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sztNLm7tN",
	md: "ISwydG9uT",
	lg: "D_qG9ecEc",
	"2xl": "qF5JknOSk",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e174c9286f577d890cd3ebd3f2bbe1795257a26f52465d7e4a58bd10905a6285"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e174c9286f577d890cd3ebd3f2bbe1795257a26f52465d7e4a58bd10905a6285"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var faq_section_default = ComponentWithRoot;
export { faq_section_default as default };
