// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project bee694db1d314f12 "Innermost AI (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-VTBEWI2D.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-POPZIQSD.js";
import "./chunks/chunk-TDPQQHTE.js";
import { className, css, fonts } from "./chunks/chunk-ZU6I45GC.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:hero
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/HERO-Flp8.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/RdZpbE6nLEjta2Tj6iC1/KKJ27spQ2UbQHS4HIVjn/mWxj5sYcJ.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Poppins-600",
	"GF;Poppins-900",
	"GF;Poppins-900italic",
	"GF;Poppins-600italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLEj6V15vFP-KUEg.woff2",
				weight: "600",
			},
			{
				family: "Poppins",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLBT5V15vFP-KUEg.woff2",
				weight: "900",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiDyp8kv8JHgFVrJJLm81xlFd2PQEhcqw.woff2",
				weight: "900",
			},
			{
				family: "Poppins",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/poppins/v23/pxiDyp8kv8JHgFVrJJLmr19lFd2PQEhcqw.woff2",
				weight: "600",
			},
		],
	},
];
var css3 = [
	'.framer-qzC5E .framer-styles-preset-nukbi7:not(.rich-text-wrapper), .framer-qzC5E .framer-styles-preset-nukbi7.rich-text-wrapper h1 { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", sans-serif; --framer-font-family-bold-italic: "Poppins", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 68px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.04em; --framer-line-height: 110%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-qzC5E .framer-styles-preset-nukbi7:not(.rich-text-wrapper), .framer-qzC5E .framer-styles-preset-nukbi7.rich-text-wrapper h1 { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", sans-serif; --framer-font-family-bold-italic: "Poppins", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 54px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.04em; --framer-line-height: 110%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-qzC5E .framer-styles-preset-nukbi7:not(.rich-text-wrapper), .framer-qzC5E .framer-styles-preset-nukbi7.rich-text-wrapper h1 { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", sans-serif; --framer-font-family-bold-italic: "Poppins", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 44px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.04em; --framer-line-height: 110%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-qzC5E";

// /:https://framer.com/m/HERO-Flp8.js
var ButtonGeneralFonts = getFonts(stdin_default);
var ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image),
);
var cycleOrder = ["RBlWU2FIF", "C8KUmnKkP", "pH8y1Tvw7", "DX7XtOKZ5"];
var serializationHash = "framer-qjGLq";
var variantClassNames = {
	C8KUmnKkP: "framer-v-12y4wjw",
	DX7XtOKZ5: "framer-v-mfuu0h",
	pH8y1Tvw7: "framer-v-n9ohrj",
	RBlWU2FIF: "framer-v-6zvehm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 50,
	delay: 0.4,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: -4,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 100,
};
var transition3 = {
	damping: 50,
	delay: 0.3,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 4,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "RBlWU2FIF",
	Medium: "C8KUmnKkP",
	Phone: "DX7XtOKZ5",
	Tablet: "pH8y1Tvw7",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RBlWU2FIF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RBlWU2FIF",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-6zvehm",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"RBlWU2FIF"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								C8KUmnKkP: {
									"data-framer-name": "Medium",
								},
								DX7XtOKZ5: {
									"data-framer-name": "Phone",
								},
								pH8y1Tvw7: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1lgnnt6"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"T5KFjzuql"}
							style={{
								background:
									"linear-gradient(180deg, rgb(36, 36, 35) 0%, rgb(0, 0, 0) 81.25%)",
								borderBottomLeftRadius: 48,
								borderBottomRightRadius: 48,
								borderTopLeftRadius: 48,
								borderTopRightRadius: 48,
							}}
							variants={{
								DX7XtOKZ5: {
									borderBottomLeftRadius: 28,
									borderBottomRightRadius: 28,
									borderTopLeftRadius: 28,
									borderTopRightRadius: 28,
								},
							}}
						>
							<motion.div
								className={"framer-bqcfw4"}
								data-framer-name={"Hero Content"}
								layoutDependency={layoutDependency}
								layoutId={"Q39si5ER7"}
							>
								<motion.div
									className={"framer-1oq6rq9"}
									data-framer-name={"content"}
									layoutDependency={layoutDependency}
									layoutId={"g7jT1doL0"}
								>
									<motion.div
										className={"framer-qijphh"}
										data-framer-name={"Hook"}
										layoutDependency={layoutDependency}
										layoutId={"J8hw1LTUc"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1py0ktj"}
											data-framer-name={"UNIQUELY PERSONAL AI"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"TDejm4GCw"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-6f861z"}
													data-styles-preset={"FQIVEzdXc"}
												>
													{"UNIQUELY PERSONAL AI"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mx7zld"}
											data-framer-name={"Don\u2019t worry, be happier"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"tRtgefOG7"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											variants={{
												DX7XtOKZ5: {
													"--extracted-gdpscs": "rgb(255, 255, 255)",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													DX7XtOKZ5: {
														children: (
															<React.Fragment>
																<motion.h1
																	style={{
																		"--font-selector": "R0Y7UG9wcGlucy02MDA=",
																		"--framer-font-family":
																			'"Poppins", "Poppins Placeholder", sans-serif',
																		"--framer-font-size": "44px",
																		"--framer-font-weight": "600",
																		"--framer-letter-spacing": "-0.04em",
																		"--framer-line-height": "110%",
																		"--framer-text-alignment": "center",
																		"--framer-text-color":
																			"var(--extracted-gdpscs, rgb(255, 255, 255))",
																	}}
																>
																	{"Don\u2019t worry, be happier"}
																</motion.h1>
															</React.Fragment>
														),
														fonts: ["GF;Poppins-600"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h1
													className={"framer-styles-preset-nukbi7"}
													data-styles-preset={"mWxj5sYcJ"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Don\u2019t worry, be happier"}
												</motion.h1>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-fiift9"}
										data-framer-name={"tagline+cta"}
										layoutDependency={layoutDependency}
										layoutId={"wNoHHCv1A"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-17gn6l4"}
											data-framer-name={
												"We are entertainment with a purpose, because working on yourself should be something you look forward to every day."
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"dqUEJ0nLl"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											variants={{
												DX7XtOKZ5: {
													"--extracted-r6o4lv":
														"var(--token-7cbc8809-805f-42b8-a101-1dbda095b6b0, rgb(247, 245, 242))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													DX7XtOKZ5: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"R0Y7UG9wcGlucy1yZWd1bGFy",
																		"--framer-font-family":
																			'"Poppins", "Poppins Placeholder", sans-serif',
																		"--framer-font-size": "20px",
																		"--framer-letter-spacing": "-0.03em",
																		"--framer-line-height": "140%",
																		"--framer-text-alignment": "center",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-7cbc8809-805f-42b8-a101-1dbda095b6b0, rgb(247, 245, 242)))",
																	}}
																>
																	{
																		"Life is tricky. We could all use help working through things. Your innermost AI guide will help you process life\u2019s moments and your personalized feed will make working on yourself something you look forward to every day."
																	}
																</motion.p>
															</React.Fragment>
														),
														fonts: ["GF;Poppins-regular"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1i5cls4"}
													data-styles-preset={"EPQDnqDHg"}
												>
													{
														"Life is tricky. We could all use help working through things. Your innermost AI guide will help you process life\u2019s moments and your personalized feed will make working on yourself something you look forward to every day."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
										<ComponentViewportProvider
											height={50}
											y={
												(componentViewport?.y || 0) +
												0 +
												0 +
												60 +
												0 +
												0 +
												0 +
												0 +
												162.8 +
												0 +
												208
											}
											{...addPropertyOverrides(
												{
													DX7XtOKZ5: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 771) - 0 - 771) /
																2 +
																0 +
																0) +
															60 +
															0 +
															0 +
															0 +
															0 +
															120.4 +
															0 +
															180,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1byhlrk-container"}
												layoutDependency={layoutDependency}
												layoutId={"HFTb1Q3G6-container"}
												nodeId={"HFTb1Q3G6"}
												rendersWithMotion={true}
												scopeId={"B4yBfDtXh"}
											>
												{_jsx(stdin_default, {
													c3NOAKqXS: "https://getinnermost.com/register",
													gCmmKaF_0: "choose your guide",
													height: "100%",
													id: "HFTb1Q3G6",
													layoutId: "HFTb1Q3G6",
													SOlgGv_mR: "14px 32px 14px 32px",
													variant: "iGf3xscni",
													width: "100%",
													...addPropertyOverrides(
														{
															DX7XtOKZ5: {
																c3NOAKqXS:
																	"https://getinnermost.com/login The \u201Cchoose your guide\u201D button and the \u201Ccreate account\u201D and the \u201Cget help now\u201D link should link to https://getinnermost.com/register",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-rh4wsr"}
								data-framer-name={"Bottom Section"}
								layoutDependency={layoutDependency}
								layoutId={"BKu0Il03R"}
							>
								<motion.div
									className={"framer-1x1yofe"}
									data-framer-name={"image cover"}
									layoutDependency={layoutDependency}
									layoutId={"TykhB1vOS"}
								>
									<ImageWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													0 +
													60 +
													430.8 +
													-0.391 +
													101,
											),
											pixelHeight: 2527,
											pixelWidth: 1415,
											sizes: "292px",
											src: "https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527",
											srcSet:
												"https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527 1415w",
										}}
										className={"framer-uboxqj"}
										data-framer-appear-id={"uboxqj"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"FAKjsMMSq"}
										optimized={true}
										style={{
											rotate: -4,
										}}
										{...addPropertyOverrides(
											{
												DX7XtOKZ5: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 771) -
																	0 -
																	771) /
																	2 +
																	0 +
																	0) +
																60 +
																360.4 +
																-1.6256 +
																83,
														),
														pixelHeight: 2527,
														pixelWidth: 1415,
														sizes: "127px",
														src: "https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527",
														srcSet:
															"https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527 1415w",
													},
												},
												pH8y1Tvw7: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																0 +
																60 +
																430.8 +
																-0.4474 +
																389.2 -
																260,
														),
														pixelHeight: 2527,
														pixelWidth: 1415,
														sizes: "252px",
														src: "https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527",
														srcSet:
															"https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/qL8JCV5jI5Uvxi8m6SjQ6iuPRw.png?width=1415&height=2527 1415w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<ImageWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation2}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													0 +
													60 +
													430.8 +
													-0.391 +
													101,
											),
											pixelHeight: 2527,
											pixelWidth: 1415,
											sizes: "292px",
											src: "https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527",
											srcSet:
												"https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527 1415w",
										}}
										className={"framer-1vai0c5"}
										data-framer-appear-id={"1vai0c5"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"yjtb41Y40"}
										optimized={true}
										style={{
											rotate: 4,
										}}
										{...addPropertyOverrides(
											{
												DX7XtOKZ5: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 771) -
																	0 -
																	771) /
																	2 +
																	0 +
																	0) +
																60 +
																360.4 +
																-1.6256 +
																88,
														),
														pixelHeight: 2527,
														pixelWidth: 1415,
														sizes: "121px",
														src: "https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527",
														srcSet:
															"https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527 1415w",
													},
												},
												pH8y1Tvw7: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																0 +
																60 +
																430.8 +
																-0.4474 +
																389.2 -
																259,
														),
														pixelHeight: 2527,
														pixelWidth: 1415,
														sizes: "252px",
														src: "https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527",
														srcSet:
															"https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=1024&width=1415&height=2527 573w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?scale-down-to=2048&width=1415&height=2527 1146w,https://framerusercontent.com/images/akpVIcyEryELRjDcbXAjWhRQJjA.png?width=1415&height=2527 1415w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<ImageWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation3}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													0 +
													60 +
													430.8 +
													-0.391 +
													42,
											),
											pixelHeight: 2418,
											pixelWidth: 1168,
											sizes: "292px",
											src: "https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418",
											srcSet:
												"https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?scale-down-to=2048&width=1168&height=2418 989w,https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418 1168w",
										}}
										className={"framer-18tdc2p"}
										data-framer-appear-id={"18tdc2p"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"UHYyxW6LI"}
										optimized={true}
										{...addPropertyOverrides(
											{
												DX7XtOKZ5: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 771) -
																	0 -
																	771) /
																	2 +
																	0 +
																	0) +
																60 +
																360.4 +
																-1.6256 +
																18,
														),
														pixelHeight: 2418,
														pixelWidth: 1168,
														sizes: "156px",
														src: "https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418",
														srcSet:
															"https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?scale-down-to=2048&width=1168&height=2418 989w,https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418 1168w",
													},
												},
												pH8y1Tvw7: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																0 +
																60 +
																430.8 +
																-0.4474 +
																389.2 -
																318,
														),
														pixelHeight: 2418,
														pixelWidth: 1168,
														sizes: "252px",
														src: "https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418",
														srcSet:
															"https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?scale-down-to=2048&width=1168&height=2418 989w,https://framerusercontent.com/images/acGAX6RoAKVqmzjQ91QUzSqhTU.png?width=1168&height=2418 1168w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
								<motion.div
									className={"framer-192dzga"}
									data-framer-name={"bottom shadow"}
									layoutDependency={layoutDependency}
									layoutId={"qb3sIKI84"}
									style={{
										background:
											"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(13, 13, 13, 0.77) 100%)",
										borderBottomLeftRadius: 48,
										borderBottomRightRadius: 48,
									}}
								/>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qjGLq.framer-lj4ej6, .framer-qjGLq .framer-lj4ej6 { display: block; }",
	".framer-qjGLq.framer-6zvehm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 80px 0px 80px; position: relative; width: 1920px; }",
	".framer-qjGLq .framer-1lgnnt6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 831px; justify-content: flex-start; max-width: 1280px; overflow: visible; padding: 60px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-bqcfw4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 60px 0px 60px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-1oq6rq9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; max-width: 840px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-qijphh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-1py0ktj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-qjGLq .framer-mx7zld, .framer-qjGLq .framer-17gn6l4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-qjGLq .framer-fiift9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-1byhlrk-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-qjGLq .framer-rh4wsr { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-qjGLq .framer-1x1yofe { flex: none; height: 100%; left: calc(50.00000000000002% - min(930px, 100%) / 2); max-width: 930px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: calc(49.88505747126439% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-qjGLq .framer-uboxqj { flex: none; height: 534px; left: 107px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 101px; width: 292px; }",
	".framer-qjGLq .framer-1vai0c5 { flex: none; height: 533px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 104px; top: 101px; width: 292px; }",
	".framer-qjGLq .framer-18tdc2p { flex: none; height: 604px; left: calc(50.00000000000002% - 292px / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 42px; width: 292px; }",
	".framer-qjGLq .framer-192dzga { bottom: 0px; flex: none; height: 69px; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-qjGLq.framer-v-12y4wjw.framer-6zvehm { padding: 0px 50px 0px 50px; width: 1120px; }",
	".framer-qjGLq.framer-v-12y4wjw .framer-1x1yofe { left: calc(50.00000000000002% - min(750px, 100%) / 2); max-width: 750px; }",
	".framer-qjGLq.framer-v-12y4wjw .framer-uboxqj { left: 18px; }",
	".framer-qjGLq.framer-v-12y4wjw .framer-1vai0c5 { right: 18px; }",
	".framer-qjGLq.framer-v-n9ohrj.framer-6zvehm { padding: 0px 30px 0px 30px; width: 810px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-1lgnnt6 { height: 880px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-bqcfw4 { padding: 0px 30px 0px 30px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-1x1yofe { left: calc(50.00000000000002% - min(640px, 100%) / 2); max-width: 640px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-uboxqj { bottom: -200px; height: 460px; left: 16px; top: unset; width: 252px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-1vai0c5 { bottom: -200px; height: 459px; right: 16px; top: unset; width: 252px; }",
	".framer-qjGLq.framer-v-n9ohrj .framer-18tdc2p { bottom: -202px; height: 520px; left: calc(50.00000000000002% - 252px / 2); top: unset; width: 252px; }",
	".framer-qjGLq.framer-v-mfuu0h.framer-6zvehm { justify-content: center; padding: 0px 20px 0px 20px; width: 390px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-1lgnnt6 { align-content: center; align-items: center; height: 771px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-bqcfw4 { padding: 0px 20px 0px 20px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-1oq6rq9 { gap: 24px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-rh4wsr { width: 350px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-1x1yofe { height: 100%; left: calc(50.00000000000002% - min(390px, 100%) / 2); max-width: 390px; top: calc(49.69135802469138% - 100.30864197530865% / 2); }",
	".framer-qjGLq.framer-v-mfuu0h .framer-uboxqj { height: 227px; left: 27px; top: 83px; width: 127px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-1vai0c5 { height: 213px; right: 27px; top: 88px; width: 121px; }",
	".framer-qjGLq.framer-v-mfuu0h .framer-18tdc2p { height: 320px; left: calc(50.00000000000002% - 156px / 2); top: 18px; width: 156px; }",
	...css2,
	...css3,
	...css,
];
var FramerB4yBfDtXh = withCSS(Component, css4, "framer-qjGLq");
var stdin_default2 = FramerB4yBfDtXh;
FramerB4yBfDtXh.displayName = "HERO";
FramerB4yBfDtXh.defaultProps = {
	height: 831,
	width: 1920,
};
addPropertyControls(FramerB4yBfDtXh, {
	variant: {
		options: ["RBlWU2FIF", "C8KUmnKkP", "pH8y1Tvw7", "DX7XtOKZ5"],
		optionTitles: ["Variant 1", "Medium", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerB4yBfDtXh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v23/pxiByp8kv8JHgFVrLEj6V15vFP-KUEg.woff2",
					weight: "600",
				},
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v23/pxiEyp8kv8JHgFVrFJXUc1NECPY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonGeneralFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "DX7XtOKZ5",
	md: "pH8y1Tvw7",
	lg: "C8KUmnKkP",
	"2xl": "RBlWU2FIF",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bee694db1d314f12b6cdffa60a360ffca3c14f0f2418539a656750f9a51be314"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bee694db1d314f12b6cdffa60a360ffca3c14f0f2418539a656750f9a51be314"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var hero_default = ComponentWithRoot;
export { hero_default as default };
