// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project bee694db1d314f12 "Innermost AI (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:journal-ideas
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/journal-ideas-X5GY.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["eiMs3pWJA", "FFcvBCrRq", "I74mHFSGR"];
var serializationHash = "framer-eaT4s";
var variantClassNames = {
	eiMs3pWJA: "framer-v-1ar99t7",
	FFcvBCrRq: "framer-v-oh7w49",
	I74mHFSGR: "framer-v-dvwn0r",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 100,
};
var transition2 = {
	damping: 50,
	delay: 0.8,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 100,
};
var transition3 = {
	damping: 50,
	delay: 0.7,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 100,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition4 = {
	damping: 50,
	delay: 0.5,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 100,
};
var transition5 = {
	damping: 50,
	delay: 0.3,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 100,
};
var transition6 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 250,
	type: "spring",
};
var animation5 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 100,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "eiMs3pWJA",
	Large: "I74mHFSGR",
	Phone: "FFcvBCrRq",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "eiMs3pWJA",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "eiMs3pWJA",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ar99t7",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"eiMs3pWJA"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FFcvBCrRq: {
									"data-framer-name": "Phone",
								},
								I74mHFSGR: {
									"data-framer-name": "Large",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation1}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-124g8fx"}
							data-framer-name={"journal idea"}
							layoutDependency={layoutDependency}
							layoutId={"gBed6ogC2"}
							style={{
								backgroundColor: "rgb(36, 36, 35)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 10px 50px 0px rgba(0, 0, 0, 0.1)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "stretch",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 361) -
											353 +
											0,
									),
									pixelHeight: 692,
									pixelWidth: 1688,
									positionX: "center",
									positionY: "center",
									sizes: `calc((${componentViewport?.width || "100vw"} - 34px) * 1.0024)`,
									src: "https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692",
									srcSet:
										"https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=512&width=1688&height=692 512w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=1024&width=1688&height=692 1024w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692 1688w",
								}}
								className={"framer-jpeirt"}
								data-framer-name={"Screenshot 2025-08-12 at 17.02.10 1"}
								layoutDependency={layoutDependency}
								layoutId={"SHLAnOkca"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								{...addPropertyOverrides(
									{
										FFcvBCrRq: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 287) -
														256 +
														0,
												),
												pixelHeight: 692,
												pixelWidth: 1688,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 34px) * 1.0024)`,
												src: "https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692",
												srcSet:
													"https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=512&width=1688&height=692 512w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=1024&width=1688&height=692 1024w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692 1688w",
											},
										},
										I74mHFSGR: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 433) -
														442 +
														0,
												),
												pixelHeight: 692,
												pixelWidth: 1688,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 34px) * 1.0024)`,
												src: "https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692",
												srcSet:
													"https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=512&width=1688&height=692 512w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?scale-down-to=1024&width=1688&height=692 1024w,https://framerusercontent.com/images/j4OqRsnNVXV8ctWILuzDPjCjs.png?width=1688&height=692 1688w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition3,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation2}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1c4awm3"}
							data-framer-name={"journal idea"}
							layoutDependency={layoutDependency}
							layoutId={"hm8cz5aHf"}
							style={{
								backgroundColor: "rgb(36, 36, 35)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 10px 50px 0px rgba(0, 0, 0, 0.1)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "stretch",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 361) -
											316 +
											0,
									),
									pixelHeight: 716,
									pixelWidth: 1768,
									positionX: "center",
									positionY: "center",
									sizes: `calc((${componentViewport?.width || "100vw"} - 26px) * 1.0023)`,
									src: "https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716",
									srcSet:
										"https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=512&width=1768&height=716 512w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=1024&width=1768&height=716 1024w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716 1768w",
								}}
								className={"framer-14kh1zb"}
								data-framer-name={"Screenshot 2025-08-12 at 17.01.52 1"}
								layoutDependency={layoutDependency}
								layoutId={"dfNEVDMac"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										FFcvBCrRq: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 287) -
														230 +
														0,
												),
												pixelHeight: 716,
												pixelWidth: 1768,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 26px) * 1.0023)`,
												src: "https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716",
												srcSet:
													"https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=512&width=1768&height=716 512w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=1024&width=1768&height=716 1024w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716 1768w",
											},
										},
										I74mHFSGR: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 433) -
														396 +
														0,
												),
												pixelHeight: 716,
												pixelWidth: 1768,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 26px) * 1.0023)`,
												src: "https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716",
												srcSet:
													"https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=512&width=1768&height=716 512w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?scale-down-to=1024&width=1768&height=716 1024w,https://framerusercontent.com/images/LI01ZsDWV9JFdREeTLFHLnTMrqQ.png?width=1768&height=716 1768w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition4,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation3}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-18n2xjq"}
							data-framer-name={"journal idea"}
							layoutDependency={layoutDependency}
							layoutId={"JeiBUFuEV"}
							style={{
								backgroundColor: "rgb(36, 36, 35)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 10px 50px 0px rgba(0, 0, 0, 0.1)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "stretch",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 361) -
											282 +
											0,
									),
									pixelHeight: 744,
									pixelWidth: 1848,
									positionX: "center",
									positionY: "center",
									sizes: `calc((${componentViewport?.width || "100vw"} - 17px) * 1.0022)`,
									src: "https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744",
									srcSet:
										"https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=512&width=1848&height=744 512w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=1024&width=1848&height=744 1024w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744 1848w",
								}}
								className={"framer-1tnortq"}
								data-framer-name={"Screenshot 2025-08-12 at 17.01.39 1"}
								layoutDependency={layoutDependency}
								layoutId={"Pz_ECH6DD"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										FFcvBCrRq: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 287) -
														199 +
														0,
												),
												pixelHeight: 744,
												pixelWidth: 1848,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 17px) * 1.0022)`,
												src: "https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744",
												srcSet:
													"https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=512&width=1848&height=744 512w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=1024&width=1848&height=744 1024w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744 1848w",
											},
										},
										I74mHFSGR: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 433) -
														351 +
														0,
												),
												pixelHeight: 744,
												pixelWidth: 1848,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 17px) * 1.0022)`,
												src: "https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744",
												srcSet:
													"https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=512&width=1848&height=744 512w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?scale-down-to=1024&width=1848&height=744 1024w,https://framerusercontent.com/images/C3UnyiblD5Ke5Qq9rNrLuQFC1MQ.png?width=1848&height=744 1848w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition5,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation4}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1nofzhh"}
							data-framer-name={"journal idea"}
							layoutDependency={layoutDependency}
							layoutId={"uZ6rWYPy5"}
							style={{
								backgroundColor: "rgb(36, 36, 35)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 10px 50px 0px rgba(0, 0, 0, 0.1)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "stretch",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 361) -
											245 +
											0,
									),
									pixelHeight: 668,
									pixelWidth: 1920,
									positionX: "center",
									positionY: "center",
									sizes: `calc((${componentViewport?.width || "100vw"} - 9px) * 1.0021)`,
									src: "https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668",
									srcSet:
										"https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=512&width=1920&height=668 512w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=1024&width=1920&height=668 1024w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668 1920w",
								}}
								className={"framer-1033we8"}
								data-framer-name={"Screenshot 2025-08-12 at 17.01.28 1"}
								layoutDependency={layoutDependency}
								layoutId={"tI0Jx8RkZ"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										FFcvBCrRq: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 287) -
														170 +
														0,
												),
												pixelHeight: 668,
												pixelWidth: 1920,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 9px) * 1.0021)`,
												src: "https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668",
												srcSet:
													"https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=512&width=1920&height=668 512w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=1024&width=1920&height=668 1024w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668 1920w",
											},
										},
										I74mHFSGR: {
											background: {
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 433) -
														300 +
														0,
												),
												pixelHeight: 668,
												pixelWidth: 1920,
												positionX: "center",
												positionY: "center",
												sizes: `calc((${componentViewport?.width || "100vw"} - 9px) * 1.0021)`,
												src: "https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668",
												srcSet:
													"https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=512&width=1920&height=668 512w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?scale-down-to=1024&width=1920&height=668 1024w,https://framerusercontent.com/images/D9DoKjiD7RORzhgwnQEHNvxBlMg.png?width=1920&height=668 1920w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition6,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation5}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-7nemxn"}
							data-framer-name={"journal idea"}
							layoutDependency={layoutDependency}
							layoutId={"dsVNxKBbk"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								boxShadow: "0px 10px 50px 0px rgba(0, 0, 0, 0.1)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 361) -
											86 +
											0,
									),
									pixelHeight: 804,
									pixelWidth: 1998,
									sizes: `calc(${componentViewport?.width || "100vw"} * 1.002)`,
									src: "https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804",
									srcSet:
										"https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=512&width=1998&height=804 512w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=1024&width=1998&height=804 1024w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804 1998w",
								}}
								className={"framer-d8yg7j"}
								data-framer-name={"Screenshot 2025-08-12 at 17.01.12 1"}
								layoutDependency={layoutDependency}
								layoutId={"M2Slf24tV"}
								style={{
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										FFcvBCrRq: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 287) -
														86 +
														0,
												),
												pixelHeight: 804,
												pixelWidth: 1998,
												sizes: `calc(${componentViewport?.width || "100vw"} * 1.002)`,
												src: "https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804",
												srcSet:
													"https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=512&width=1998&height=804 512w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=1024&width=1998&height=804 1024w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804 1998w",
											},
										},
										I74mHFSGR: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 433) -
														86 +
														0,
												),
												pixelHeight: 804,
												pixelWidth: 1998,
												sizes: `calc(${componentViewport?.width || "100vw"} * 1.002)`,
												src: "https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804",
												srcSet:
													"https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=512&width=1998&height=804 512w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?scale-down-to=1024&width=1998&height=804 1024w,https://framerusercontent.com/images/0miQJXVMhgRh9vfxTn17gdSX3F4.png?width=1998&height=804 1998w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</MotionDivWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eaT4s.framer-mkrwa8, .framer-eaT4s .framer-mkrwa8 { display: block; }",
	".framer-eaT4s.framer-1ar99t7 { height: 361px; overflow: visible; position: relative; width: 508px; }",
	".framer-eaT4s .framer-124g8fx { aspect-ratio: 2.433526011560694 / 1; bottom: 158px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 195px); left: 17px; overflow: visible; position: absolute; right: 17px; }",
	".framer-eaT4s .framer-jpeirt { aspect-ratio: 2.437317790949522 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; left: 0px; position: absolute; top: 0px; width: 100%; }",
	".framer-eaT4s .framer-1c4awm3 { aspect-ratio: 2.4775280898876404 / 1; bottom: 121px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 195px); left: 13px; overflow: visible; position: absolute; right: 13px; }",
	".framer-eaT4s .framer-14kh1zb { aspect-ratio: 2.478378229210482 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-eaT4s .framer-18n2xjq { aspect-ratio: 2.478494623655914 / 1; bottom: 84px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 198px); left: 9px; overflow: visible; position: absolute; right: 8px; }",
	".framer-eaT4s .framer-1tnortq { aspect-ratio: 2.485094824885718 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-eaT4s .framer-1nofzhh { aspect-ratio: 2.8682634730538923 / 1; bottom: 71px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 174px); left: 5px; overflow: hidden; position: absolute; right: 4px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eaT4s .framer-1033we8 { aspect-ratio: 2.8710694272904833 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-eaT4s .framer-7nemxn { aspect-ratio: 2.482587064676617 / 1; bottom: -1px; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 205px); left: 0px; overflow: hidden; position: absolute; right: 0px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eaT4s .framer-d8yg7j { aspect-ratio: 2.4877384797001327 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-eaT4s.framer-v-oh7w49.framer-1ar99t7 { height: 287px; width: 350px; }",
	".framer-eaT4s.framer-v-oh7w49 .framer-124g8fx { bottom: 126px; height: var(--framer-aspect-ratio-supported, 130px); }",
	".framer-eaT4s.framer-v-oh7w49 .framer-1c4awm3 { bottom: 99px; height: var(--framer-aspect-ratio-supported, 131px); }",
	".framer-eaT4s.framer-v-oh7w49 .framer-18n2xjq { bottom: 65px; height: var(--framer-aspect-ratio-supported, 134px); }",
	".framer-eaT4s.framer-v-oh7w49 .framer-1nofzhh { bottom: 51px; height: var(--framer-aspect-ratio-supported, 119px); }",
	".framer-eaT4s.framer-v-oh7w49 .framer-7nemxn { height: var(--framer-aspect-ratio-supported, 141px); }",
	".framer-eaT4s.framer-v-dvwn0r.framer-1ar99t7 { height: 433px; width: 630px; }",
	".framer-eaT4s.framer-v-dvwn0r .framer-124g8fx { bottom: 197px; height: var(--framer-aspect-ratio-supported, 245px); }",
	".framer-eaT4s.framer-v-dvwn0r .framer-1c4awm3 { bottom: 152px; height: var(--framer-aspect-ratio-supported, 244px); }",
	".framer-eaT4s.framer-v-dvwn0r .framer-18n2xjq { bottom: 104px; height: var(--framer-aspect-ratio-supported, 247px); }",
	".framer-eaT4s.framer-v-dvwn0r .framer-1nofzhh { bottom: 84px; height: var(--framer-aspect-ratio-supported, 216px); }",
	".framer-eaT4s.framer-v-dvwn0r .framer-7nemxn { height: var(--framer-aspect-ratio-supported, 254px); }",
];
var FramerjiLC6i7Fp = withCSS(Component, css, "framer-eaT4s");
var stdin_default = FramerjiLC6i7Fp;
FramerjiLC6i7Fp.displayName = "journal ideas";
FramerjiLC6i7Fp.defaultProps = {
	height: 361,
	width: 508,
};
addPropertyControls(FramerjiLC6i7Fp, {
	variant: {
		options: ["eiMs3pWJA", "FFcvBCrRq", "I74mHFSGR"],
		optionTitles: ["Variant 1", "Phone", "Large"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerjiLC6i7Fp,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:journal-ideas
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FFcvBCrRq",
	md: "I74mHFSGR",
	"2xl": "eiMs3pWJA",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bee694db1d314f12b6cdffa60a360ffca3c14f0f2418539a656750f9a51be314"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders JournalIdeasFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bee694db1d314f12b6cdffa60a360ffca3c14f0f2418539a656750f9a51be314"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var journal_ideas_default = ComponentWithRoot;
export { journal_ideas_default as default };
